sudo: false
cache:
  pip: true
language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - make install
script:
  - make test
  - make coverage
after_success:
  - pip install coveralls
  - coveralls
